name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Setup
          run: npm install
        - name: Test
          run: npm run wdio
          env:
            ENV_PATH: environment/QS
        - name: Upload Test Reports
          if: success() || failure() 
          uses: actions/upload-artifact@v2
          with:
            name: reports
            path: .tmp/report/
        - name: Upload Logs
          if: success() || failure() 
          uses: actions/upload-artifact@v2
          with:
            name: logs
            path: log/
        - name: Upload GitHub Pages artifact
          if: success() || failure() 
          uses: actions/upload-pages-artifact@v3.0.1
    