name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm ci
        - name: Test
          run: npm run ${{ matrix.exampleDir }}
          working-directory: ${{ matrix.exampleDir }}
        - name: 🐛 Debug Build
          uses: stateful/vscode-server-action@v1
          if: failure()
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: ${{ matrix.exampleDir }}/logs