name: CI
on: [push, pull_request]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  setup:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        run: npm install
      - name: Test
        run: npm run wdio
  generate-report:
    if: success() || failure()
    needs: [setup, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload GitHub Pages artifact
        if: success() || failure() 
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: artifact/
  publish-report:
    if: success() || failure() 
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        if: success() || failure()
        id: deployment
        uses: actions/deploy-pages@v4


    