name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          # with:
          #   name: Junit Tests            # Name of the check run which will be created
          #   path: '**/target/surefire-reports/TEST-*.xml'
          #   reporter: java-junit