name: CI
on: [push, pull_request]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        run: npm install
      - name: Test
        run: npm run wdio
        env:
          ENV_PATH: environment/QS
      # - name: Upload Test Reports
      #   if: success() || failure() 
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: github-pages
      #     path: .tmp/report/
      - name: Upload GitHub Pages artifact
        if: success() || failure() 
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: .tmp/report/
      - name: Deploy to GitHub Pages
        if: success() || failure()
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   name: _site
        #   path: .tmp/report/
    